pyhoh:
  profiles:
    default:
      # osc input that takes video control commands
      omxvideo_osc_inputs:
        self:
          ip: ''
          port: 2030
          verbose: true

      # send osc messages
      osc_outputs:
        bcast_and_local:
          verbose: true
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2030

      # video playback component
      omxvideo:
        verbose: true
        playlist:
          - '/home/pi/videos/vid1.mov'
          - '/home/pi/videos/vid2.mov'
          - '/home/pi/videos/vid3.mov'
          - '/home/pi/videos/vid4.mov'
          - '/home/pi/videos/vid5.mov'

      omxsyncer:
        master: true
        verbose: true

      midi_inputs:
        vidmidi:
          port: 1
          verbose: true

      midi_to_osc:
        # akai pads (prog1)
        vidmidi:
          144: # midi message type; note on
            36: '/pyhoh/vid/start/0' # prog1, pad1
            37: '/pyhoh/vid/start/1'
            38: '/pyhoh/vid/start/2'
            39: '/pyhoh/vid/start/3'
            40: '/pyhoh/vid/start/4'
            41: '/pyhoh/vid/pause'
            42: '/pyhoh/vid/stop'
            43: '/pyhoh/vid/stop'

    master:
      # osc input that takes video control commands
      omxvideo_osc_inputs:
        self:
          ip: ''
          port: 2030
          verbose: true

      # send osc messages
      osc_outputs:
        bcast_and_local:
          verbose: true
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2030

      # video playback component
      omxvideo:
        verbose: true
        playlist:
          - '/home/pi/videos/vid1.mov'
          - '/home/pi/videos/vid2.mov'
          - '/home/pi/videos/vid3.mov'
          - '/home/pi/videos/vid4.mov'
          - '/home/pi/videos/vid5.mov'

      omxsyncer:
        master: true
        verbose: true

      midi_inputs:
        vidmidi:
          port: 1
          verbose: true

      midi_to_osc:
        # akai pads (prog1)
        vidmidi:
          144: # midi message type; note on
            36: '/pyhoh/vid/start/0' # prog1, pad1
            37: '/pyhoh/vid/start/1'
            38: '/pyhoh/vid/start/2'
            39: '/pyhoh/vid/start/3'
            40: '/pyhoh/vid/start/4'
            41: '/pyhoh/vid/pause'
            42: '/pyhoh/vid/stop'
            43: '/pyhoh/vid/stop'

    slave:
      # osc input that takes video control commands
      omxvideo_osc_inputs:
        self:
          ip: ''
          port: 2030
          verbose: true

      # video playback component
      omxvideo:
        verbose: true
        playlist:
          - '/home/pi/videos/vid1.mov'
          - '/home/pi/videos/vid2.mov'
          - '/home/pi/videos/vid3.mov'
          - '/home/pi/videos/vid4.mov'
          - '/home/pi/videos/vid5.mov'

      omxsyncer:
        slave: true
        verbose: true
