pyhoh:
  profiles:
    default:
      # osc input that takes video control commands
      omxvideo_osc_inputs:
        self:
          ip: ''
          port: 2030
          verbose: true

      # send osc messages
      osc_outputs:
        bcast_and_local:
          # verbose: true
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2030

      # video playback component
      omxvideo:
        verbose: true
        playlist:
          - '/home/pi/videos/vid1.mov'
          - '/home/pi/videos/vid2.mov'
          - '/home/pi/videos/vid3.mov'

      omxsync:
        master: true
        verbose: true

      midi_inputs:
        vidmidi:
          port: 1
          verbose: true
