pyhoh:
  profiles:
    default:

      delay_events:
        looper: # name/ID
          source: 'loop'
          delay: 60 # seconds
          target: 'loop'
          halt: 'stop'
          pause: 'pause'

      event_to_event:
        'start': ['load', 'loop']
        'stop': ['stoploop', 'unload']

      # video playback component
      omxvideo:
        verbose: true
        args: ['--no-osd', '--adev', 'local', '-b']
        playlist:
          - '/home/pi/videos/vid1.mov'
          - '/home/pi/videos/vid2.mov'
          - '/home/pi/videos/vid3.mov'
          - '/home/pi/videos/vid4.mov'
          - '/home/pi/videos/vid5.mov'

      # send osc messages
      osc_outputs:
        bcast_and_local:
          verbose: true
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2030

      omx_osc_output:
        bcast_and_local:
          verbose: true
          start: '/pyhoh/vid/start'
          pause: '/pyhoh/vid/pause'
          stop: '/pyhoh/vid/stop'

      midi_inputs:
        akai:
          port: 1
          verbose: true

      midi_to_event:
        akai:
          verbose: true
          144: # midi message type; note on
            36: 'start0' # midi note 36 triggers event start0
            37: 'start1'
            38: 'start2'
            39: 'start3'
            40: 'start4'
            41: 'pause'
            42: 'stop'
            43: 'stop'

      midi_to_omx:
        # akai pads (prog1)
        akai:
          verbose: true
          144: # midi message type; note on
            36:
              action: 'start'
              params:
                - 0
            37:
              action: 'start'
              params:
                - 1
            38:
              action: 'start'
              params:
                - 2
            39:
              action: 'start'
              params:
                - 3
            40:
              action: 'start'
              params:
                - 4
            41:
              action: 'pause'
            42:
              action: 'stop'
            43:
              action: 'stop'
