pyhoh:
  profiles:
    default:
      omxvideo_osc_inputs:
        self:
          ip: ''
          port: 2030
          verbose: true
      omxvideo:
        verbose: true
        playlist:
          - '/home/pi/videos/vid1.mov'
          - '/home/pi/videos/vid2.mov'
          - '/home/pi/videos/vid3.mov'
