py2030:
  profiles:
    raspberrypi:
      start_event_: 'cmd-reset-up'

      lightCeremonyControllers__:
        theOne:
          verbose: true
          resetUpMaxDuration: 10.0 # seconds
          input_events:
            resetUp: 'cmd-reset-up'
            resetUpStop: 'cmd-reset-up-stop'
            resetDown: 'cmd-reset-down'
            resetDownStop: 'cmd-reset-down-stop'
            togglePlayShow: 'cmd-play-pause'
            stopShow: 'cmd-stop'

      lightCeremonyDmxOutputs:
        theOne:
          verbose: true
          fps: 10.0
          deviceName: '/dev/ttyUSB0'
          channel_event_prefix: 'ch'
          num_channels: 24
          winchStartChannel: 1
          rotatorStartChannel: 10
          input_events:
            winchVelocity: 'winchVel'
            winchResetUpVelocity: 'winchResetUpVel'
            winchResetDownVelocity: 'winchResetDownVel'
            rotatorVelocity: 'rotVel'

      sines:
        sineLight:
          verbose: false
          frequency: 0.2
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.3
          base: 0.3
          cursorStart: -0.5
          output_events:
            'value': 'ch23'

        sineWinchVelocity:
          verbose: false
          frequency: 0.1
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.1
          base: -0.032
          cursorStart: 0.0
          output_events:
            'value': 'winchVel'

        sineRotatorVelocity:
          verbose: false
          frequency: 0.1
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.8
          base: 0
          cursorStart: 0.0
          output_events:
            'value': 'rotVel'

    default:
      start_event_: 'cmd-reset-up'

      lightCeremonyControllers__:
        theOne:
          verbose: true
          resetUpMaxDuration: 10.0 # seconds
          input_events:
            resetUp: 'cmd-reset-up'
            resetUpStop: 'cmd-reset-up-stop'
            resetDown: 'cmd-reset-down'
            resetDownStop: 'cmd-reset-down-stop'
            togglePlayShow: 'cmd-play-pause'
            stopShow: 'cmd-stop'

      lightCeremonyDmxOutputs:
        theOne:
          verbose: true
          fps: 10.0
          deviceName: '/dev/cu.usbserial-EN114902'
          channel_event_prefix: 'ch'
          num_channels: 24
          winchStartChannel: 1
          rotatorStartChannel: 10
          input_events:
            winchVelocity: 'winchVel'
            winchResetUpVelocity: 'winchResetUpVel'
            winchResetDownVelocity: 'winchResetDownVel'
            rotatorVelocity: 'rotVel'

      sines:
        sineLight:
          verbose: false
          frequency: 0.2
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.3
          base: 0.3
          cursorStart: -0.5
          output_events:
            'value': 'ch23'

        sineWinchVelocity:
          verbose: false
          frequency: 0.1
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.1
          base: -0.032
          cursorStart: 0.0
          output_events:
            'value': 'winchVel'

        sineRotatorVelocity:
          verbose: false
          frequency: 0.1
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.8
          base: 0
          cursorStart: 0.0
          output_events:
            'value': 'rotVel'
