py2030:
  profiles:
    default:
      file_frame_reader:
        reader1:
          verbose: true
          file: 'anim.csv'
        output_events:
          frame: 'frame'

      dmx_outputs_DISABLED:
        dmx1:
          verbose: true
          fps: 2.0
          deviceName: 'cu.usbserial-EN114902'
          deviceNumber_: 0
          channel_event_prefix: 'ch'
          num_channels: 24

      lightCeremonyDmxOutputs:
        theOne:
          verbose: false
          fps: 2.0
          deviceName: '/dev/cu.usbserial-EN114902'
          deviceNumber_: 0
          channel_event_prefix: 'ch'
          num_channels: 24
          winchVelocityEvent: 'winchVel'
          winchStartChannel: 1

      sines:
        sineLight:
          verbose: true
          frequency: 0.1
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.2
          base: 0.2
          output_events:
            'value': 'ch24'

      sines_:
        sineWinchVelocity:
          verbose: true
          frequency: 0.1
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 1.0
          base: 0.0
          output_events:
            'value': 'winchVel'

        sineRotatorVelocity:
          verbose: true
          frequency: 0.01
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.2
          base: 0.3
          output_events:
            'value': 'ch14'

        sineLight:
          verbose: true
          frequency: 6.0
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.5
          base: 0.5
          output_events:
            'value': 'ch23'

        # sine2:
        #   verbose: false
        #   frequency: 10.5
        #   sleep: 0.3
        #   output_events:
        #     'value': 'ch2'
