py2030:
  profiles:
    default:
      file_frame_reader:
        reader1:
          verbose: true
          file: 'anim.csv'
        output_events:
          frame: 'frame'

      dmx_outputs_DISABLED:
        dmx1:
          verbose: true
          fps: 2.0
          deviceName: 'cu.usbserial-EN114902'
          deviceNumber_: 0
          channel_event_prefix: 'ch'
          num_channels: 24

      lightCeremonyDmxOutputs:
        theOne:
          verbose: true
          fps: 2.0
          deviceName: '/dev/cu.usbserial-EN114902'
          deviceNumber_: 0
          channel_event_prefix: 'ch'
          num_channels: 24
          winchVelocityEvent: 'winchVel'
          winchStartChannel: 1

      sines:
        sineLight:
          verbose: true
          frequency: 0.1
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.2
          base: 0.2
          output_events:
            'value': 'ch23' # should be 23?!

        sineWinchVelocity:
          verbose: true
          frequency: 0.1
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.1
          base: -0.032
          cursorStart: 3.0
          output_events:
            'value': 'winchVel'

        sineWinchVelocity_almost_in_balance:
          verbose: true
          frequency: 0.1
          sleep_DISABLED_BLOCKING: 1.0
          amplitude: 0.1
          base: -0.032
          cursorStart: 3.0
          output_events:
            'value': 'winchVel_DISABLED'
